#!/bin/sh

if [ $EUID -eq 0 ]; then
    echo "You cannot run makepkg as root."
    echo "Please run this script again as a non-elevated user"
    exit 1
fi

# Install dependencies
sudo pacman -S --asdeps git curl yajl gnupg

# Get PGP keys so it builds
gpg --keyserver hkp://pgp.mit.edu --recv-keys 1EB2638FF56C0C53

# Fetch, build and install cower
git clone https://aur.archlinux.org/cower.git
cd cower
makepkg -sri

# Fetch, build and install pacaur
cd ..
git clone https://aur.archlinux.org/pacaur.git
cd pacaur
makepkg -sri

cd ..
rm -rf cower pacaur
