#!/bin/sh

if [[ $EUID -ne 0 ]]; then
    echo "You must run this script on the arch install disk as a root user!"
    #exit 1
fi

# Warn about not running on the arch install disk
if [[ $(hostname) != "archiso" ]]; then
    read -p "Not running on the arch install ISO, are you sure you want to continue? [y/N] " yn
    case $yn in
        [Yy]* ) break;;
            * ) exit;;
    esac
fi

checknet() {
    curl google.com &>/dev/null
    return $?
}

# Check for an internet connection
if ! checknet; then
    echo -e "No internet connection\nPlease connect a network interface and try again"
    exit 1
fi

# Confirm all partitions are mounted to /mnt
read -p "`echo $'\n'` > Are all partitions mounted to /mnt? [y/N] " yn
case $yn in
    [Yy]* ) break;;
        * ) echo "Please mount all mountpoints to /mnt and retry"; exit;;
esac

# Install system and some basic packages
echo -e "\n > Installing base system packages"
pacstrap -i /mnt base base-devel zsh git vim btrfs-progs sudo openssh

# Generate the fstab
echo -e "\n > Generating fstab"
genfstab -U /mnt > /mnt/etc/fstab

echo -e "\n > Entering chroot...\n"

# Copy the chroot script into the new root
dir=`dirname ${BASH_SOURCE[0]}`
cp -r $dir /mnt/root
arch-chroot /mnt /root/$(basename $dir)/osinstall-chroot

# Reboot
read -p "`echo $'\n'` > Reboot? [Y/n] " yn
case $yn in
    [Nn]* ) break;;
        * ) umount -R /mnt;
            systemctl reboot;;
esac
