#!/bin/sh

# Set the hostname
read -p "`echo $'\n'` > Enter the hostname: " hostname
echo "Setting the hostname..."
echo "$hostname" > /etc/hostname

# Set the localtime to London
echo -e "\n > Setting the timezone"
ln -sfv /usr/share/zoneinfo/Europe/London /etc/localtime

# Run locale-gen
echo -e "\n > Setting the system locale"
sed -i 's|#\(en_GB.UTF-8.*\)|\1|' /etc/locale.gen
locale-gen
echo LANG=en_GB.UTF-8 > /etc/locale.conf

echo -e "\n > Setting the system keymap"
echo "KEYMAP=dvorak-uk" > /etc/vconsole.conf

read -p "`echo $'\n'` > Do you want to edit the mkinitcpio build hooks? [y/N] " yn
sed -i 's|^\(HOOKS=".* block\).*\(filesystems.*"\)|\1 keymap keyboard encrypt lvm2 btrfs \2|' /etc/mkinitcpio.conf
sed -i '/^HOOKS=".*"/s/filesystems keyboard/filesystems/' /etc/mkinitcpio.conf
case $yn in
    [Yy]* ) vim /etc/mkinitcpio.conf; break;;
        * ) break;;
esac
# Build initial ramdisk
echo -e "\n > Building initial ramdisk"
read -p " > Enter the kernel name [default: linux] " kernel
[[ -z $kernel ]] && kernel="linux"
mkinitcpio -p $kernel

# Set the root password
echo -e "\n > Please set the root password"
passwd 


# Install bootloader
read -p "`echo $'\n'` > Do you want to install rEFInd bootloader? [y/N] " yn
case $yn in
    [Yy]* ) ./osinstall-refind;;
        * ) break;;
esac

echo -e "\n > Starting shell. Type 'exit' to continue installation"
/usr/bin/zsh
