#!/bin/sh

# Symlink vim to vi
ln -sfv `which vim` /usr/bin/vi

# Enable pacman colours & multilib
sed -i '/#Color/s/^#//' /etc/pacman.conf
sed -i -e '/^#\[multilib\]/{s/#//;N;s/#//}' /etc/pacman.conf

# Don't compress with makepkg
sed -i "/PKGEXT='.pkg.tar.xz'/s/.xz//" /etc/makepkg.conf

# Give wheel sudo access
sed -i '/# %wheel ALL=(ALL) ALL/s/^# //' /etc/sudoers
sed -i '/%wheel ALL=(ALL) ALL/a %wheel ALL = NOPASSWD: /usr/bin/efibootmgr, /usr/bin/pacman' /etc/sudoers
