#!/bin/sh

if [ $EUID -eq 0 ]; then
    ./userinstall-root

    read -p " > Enter username for new user: " user
    useradd -m -G wheel -s `which zsh` $user
    passwd $user

    # Copy script to new user home directory
    home="/home/$user"
    cd $(dirname $0)
    dir="$(basename `pwd`)"
    script="$(basename $0)"
    cp -r ../$dir $home
    chown -R $user:$user $home/$dir

    echo -e "\n > Switching to new user:"
    sudo -u $user $home/$dir/$script
    exit 0
fi

echo -e "\n > Installing pacaur"
./install-pacaur

echo -e "\n > Installing system packages"

gpg --keyserver pgp.mit.edu --recv-keys F7E48EDB # ncurses5-compat-libs
pacaur -S `xargs -a sys-packages` --needed

read -p " > Do you want to install core appliactions? [Y/n] " yn
[[ $yn =~ "[nN]*" ]] || pacaur -S `xargs -a coreapps` --needed

read -p " > Do you want to install extra appliactions? [y/N] " yn
[[ $yn =~ "[yY]*" ]] && pacaur -S `xargs -a extraapps` --needed

echo -e "\n > Starting a shell, use this to generate/copy SSH keys then exit when done:"
cd ~
mkdir -p ~/.ssh
$SHELL

echo -e "\n > Setting key file permissions"
chmod 700 ~/.ssh
chmod 400 ~/.ssh/id_*
chmod 644 ~/.ssh/id_*.pub

mkdir -p ~/.config
git clone git@github.com:frebib/dotfiles.git ~/.config/dotfiles

cd ~/.config/dotfiles

echo -e "\n > Linking dotfiles"
scripts/linkdotfiles
scripts/vim-setup
